# Site settings
title:       tudr.co
email:       tudor@saitoc.me
author:      Tudor Saitoc
description: "[WIP] Knowledge sharing user experience"
baseurl:     /
url:         "https://m.tudr.co"
date_format: "%b %-d, %Y"
permalink: none

# Google services

# google_analytics: 
# google_verification:

# # Social icons
github_username: tudr
facebook_username: tudorsnyc
twitter_username: tudorsynyc
google_plus_id: 115412277589967176743

# Categories to loop
lessons :
  - pascal
  - pasir

defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
sass:
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-feed
